### ISSUE TITLE
Update Documentation for enable ArgoCd Notifcation

### ISSUE THREAD

**Issue by FaGru3n** [catenax-ng/k8s-cluster-stack#377]
**Enable ArgoCd Documentation is outdated**
By testing and enabling the Notification for IRS-Team we should update the guide to enable webhook in our repository 
https://github.com/catenax-ng/product-onboarding/blob/main/argocd/enable-argocd-notifications.md

**Describe the solution you'd like**
Modify changes to our actual doing to store the information for the hole Team

More things to know:
https://argocd-notifications.readthedocs.io/en/latest/services/teams/

**Comment by almadigabor** [comment]
@FaGru3n is this issue still relevant? Argo notifications are already enabled. Did we provide some sort of documentation for it?
